# Generated by Django 3.2.8 on 2021-12-06 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpondok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pngm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pngm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpondok.pengumuman')),
            ],
        ),
    ]
