# Generated by Django 3.2.8 on 2021-12-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pngm',
        ),
    ]
