# Generated by Django 3.2.8 on 2021-12-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('ktgri', models.CharField(choices=[('Al-Quran', 'Al-Quran'), ('Matan', 'Matan'), ('Nadhom', 'Nadhom')], default='', max_length=8, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nadzom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kitab', models.IntegerField(default=0, null=True, unique=True)),
                ('nama_kitab', models.CharField(max_length=30, null=True, unique=True)),
                ('kategori_kitab', models.CharField(choices=[('Dasar', 'Dasar'), ('Menengah', 'Menengah'), ('Atas', 'Atas')], default='', max_length=9, null=True)),
                ('jumlah_bab', models.IntegerField(default=0)),
                ('jumlah_fashol', models.IntegerField(default=0, null=True)),
                ('jumlah_bait', models.IntegerField(default=0, null=True)),
                ('nama_pengarang', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Kitab',
        ),
        migrations.AlterField(
            model_name='pengajar',
            name='NIP',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='ktgri',
            field=models.CharField(choices=[('qr', 'Al-Quran'), ('mt', 'Matan'), ('nd', 'Nadhom')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='santri',
            name='nis',
            field=models.IntegerField(unique=True),
        ),
    ]
