# Generated by Django 3.2.3 on 2021-12-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0002_auto_20211205_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santri',
            name='ktgri',
        ),
        migrations.AddField(
            model_name='santri',
            name='ktgri',
            field=models.CharField(choices=[('Al-Quran', 'Al-Quran'), ('Matan', 'Matan'), ('Nadhom', 'Nadhom')], default='', max_length=8),
        ),
        migrations.DeleteModel(
            name='SantriKg',
        ),
    ]
