# Generated by Django 3.2.8 on 2021-12-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0002_auto_20211216_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadzom',
            name='jumlah_bait',
            field=models.IntegerField(default=0),
        ),
    ]
