# Generated by Django 3.2.8 on 2021-12-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0003_alter_nadzom_jumlah_bait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadzom',
            name='jumlah_bait',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
