# Generated by Django 3.2.3 on 2021-12-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0004_auto_20211212_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santri',
            name='ktgri',
            field=models.CharField(choices=[('qr', 'Al-Quran'), ('mt', 'Matan'), ('nd', 'Nadhom')], default='', max_length=30),
        ),
    ]
