# Generated by Django 3.2.8 on 2021-12-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0005_alter_santri_ktgri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitab',
            name='jenis_kitab',
        ),
        migrations.AddField(
            model_name='kitab',
            name='jumlah_bab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kitab',
            name='jumlah_bait',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kitab',
            name='jumlah_fashol',
            field=models.IntegerField(default=0),
        ),
    ]
