# Generated by Django 3.2.8 on 2021-12-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0006_alter_nadzom_jumlah_bait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kitab', models.IntegerField(default=0, null=True, unique=True)),
                ('nama_kitab', models.CharField(max_length=30, null=True, unique=True)),
                ('kategori_kitab', models.CharField(choices=[('Dasar', 'Dasar'), ('Menengah', 'Menengah'), ('Atas', 'Atas')], default='', max_length=9, null=True)),
                ('jumlah_bab', models.IntegerField(default=0, null=True)),
                ('jumlah_fashol', models.IntegerField(default=0, null=True)),
                ('jumlah_bait', models.IntegerField(default=0, null=True)),
                ('nama_pengarang', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
