# Generated by Django 3.2.3 on 2021-12-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0006_alter_nadzom_jumlah_bait'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
