# Generated by Django 3.2.3 on 2021-12-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0007_delete_kategori'),
        ('adminpondok', '0007_matan'),
    ]

    operations = [
    ]
