<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-12-25 02:10
=======
# Generated by Django 3.2.8 on 2021-12-26 03:20
>>>>>>> 079ad95568e5877dc0ec28f955ebafba2f640dd5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0008_merge_0007_delete_kategori_0007_matan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktgri', models.CharField(choices=[('Dasar', 'Dasar'), ('Menengah', 'Menengah'), ('Atas', 'Atas')], default='', max_length=20)),
            ],
        ),
    ]
