# Generated by Django 3.2.8 on 2021-12-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0010_auto_20211228_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajar',
            name='pngjr',
            field=models.CharField(default='', max_length=50),
        ),
    ]
