# Generated by Django 3.2.3 on 2021-12-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0011_alter_pengajar_pngjr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajar',
            name='pngjr',
            field=models.CharField(choices=[('qr', 'Al-Quran'), ('mt', 'Matan'), ('nd', 'Nadhom')], default='', max_length=30),
        ),
    ]
