# Generated by Django 3.2.3 on 2022-01-01 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0012_alter_pengajar_pngjr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori_Kitab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_kitab', models.CharField(choices=[('Dasar', 'Dasar'), ('Menengah', 'Menengah'), ('Atas', 'Atas')], default='', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='matan',
            old_name='jumlah_bait',
            new_name='jumlah_halaman',
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='ktgri',
        ),
        migrations.RemoveField(
            model_name='matan',
            name='jumlah_fashol',
        ),
        migrations.RemoveField(
            model_name='matan',
            name='kode_kitab',
        ),
        migrations.RemoveField(
            model_name='nadzom',
            name='jumlah_fashol',
        ),
        migrations.RemoveField(
            model_name='nadzom',
            name='kode_kitab',
        ),
        migrations.RemoveField(
            model_name='pengajar',
            name='pngjr',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='ktgri',
        ),
        migrations.AddField(
            model_name='kategori',
            name='kategori',
            field=models.CharField(choices=[('Quran', 'AlQuran'), ('Matan', 'Matan'), ('Nadzom', 'Nadzom')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pengajar',
            name='kategori',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='kategori_pengajar', to='adminpondok.kategori'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='santri',
            name='kategori',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='kategori_santri', to='adminpondok.kategori'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nadzom',
            name='jumlah_bait',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pengajar',
            name='jk',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='matan',
            name='kategori_kitab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='matan', to='adminpondok.kategori_kitab'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nadzom',
            name='kategori_kitab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='nadzom', to='adminpondok.kategori_kitab'),
            preserve_default=False,
        ),
    ]
