# Generated by Django 3.2.3 on 2022-01-01 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0014_auto_20220101_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitab_matan', to='adminpondok.matan')),
                ('nadzom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitab_nadzom', to='adminpondok.nadzom')),
            ],
        ),
    ]
