# Generated by Django 3.2.3 on 2022-01-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0016_auto_20220101_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='kategori',
            field=models.CharField(choices=[('Quran', 'AlQuran'), ('Matan', 'Matan'), ('Nadzom', 'Nadzom')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='santri',
            name='kategori',
            field=models.CharField(choices=[('Quran', 'AlQuran'), ('Matan', 'Matan'), ('Nadzom', 'Nadzom')], default='', max_length=30),
        ),
    ]
