# Generated by Django 3.2.3 on 2022-01-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0017_auto_20220101_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SantriNgaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='matan',
            name='kategori_kitab',
        ),
        migrations.RemoveField(
            model_name='nadzom',
            name='kategori_kitab',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='kategori',
        ),
        migrations.AlterField(
            model_name='kategori',
            name='kategori',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Kategori_Kitab',
        ),
        migrations.AddField(
            model_name='santringaji',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memilih', to='adminpondok.kategori'),
        ),
        migrations.AddField(
            model_name='santringaji',
            name='santri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilih', to='adminpondok.santri'),
        ),
    ]
