# Generated by Django 3.2.3 on 2022-01-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengajar', '0008_auto_20220114_1614'),
        ('adminpondok', '0018_auto_20220114_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alquran',
        ),
        migrations.DeleteModel(
            name='Pengajar',
        ),
        migrations.RemoveField(
            model_name='kitab',
            name='matan',
        ),
        migrations.RemoveField(
            model_name='kitab',
            name='nadzom',
        ),
        migrations.AddField(
            model_name='kitab',
            name='kategori',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='termasuk', to='adminpondok.kategori'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitab',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='masuk', to='adminpondok.level'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Matan',
        ),
        migrations.DeleteModel(
            name='Nadzom',
        ),
    ]
