# Generated by Django 3.2.3 on 2022-01-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0019_auto_20220114_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='kategori',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='memilih', to='adminpondok.kategori'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SantriNgaji',
        ),
    ]
