# Generated by Django 3.2.8 on 2021-11-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengajar',
            old_name='noind_pengajar',
            new_name='NIP',
        ),
    ]
