# Generated by Django 3.2.8 on 2021-11-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kitab', models.IntegerField()),
                ('nama_kitab', models.CharField(default='', max_length=30)),
                ('Nama_Pengarang', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
