# Generated by Django 3.2.8 on 2021-11-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajar',
            name='pngjr',
            field=models.CharField(default='', max_length=10),
        ),
    ]
