# Generated by Django 3.2.3 on 2021-11-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santri',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
