# Generated by Django 3.2.3 on 2021-11-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.CharField(default='', max_length=12)),
                ('ayat', models.IntegerField(default=0, max_length=12)),
            ],
        ),
        migrations.RenameModel(
            old_name='Pengajar1',
            new_name='Pengajar',
        ),
    ]
