# Generated by Django 3.2.8 on 2021-11-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0002_pengajar_pngjr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateField()),
                ('pngmn', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
