# Generated by Django 3.2.8 on 2021-11-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0002_kitab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitab',
            old_name='Nama_Pengarang',
            new_name='nama_pengarang',
        ),
    ]
