# Generated by Django 3.2.3 on 2021-12-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0002_auto_20211201_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='ktgri',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='termasuk', to='adminpondok.kategori'),
        ),
    ]
