# Generated by Django 3.2.3 on 2021-11-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0002_auto_20211123_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquran',
            name='ayat',
            field=models.IntegerField(default=0),
        ),
    ]
