# Generated by Django 3.2.3 on 2021-11-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0003_pengumuman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santri',
            name='ktgri',
            field=models.CharField(choices=[('Quran', 'Al-Quran'), ('Matan', 'Matan'), ('Nadhom', 'Nadhom')], default='', max_length=8),
        ),
    ]
