# Generated by Django 3.2.3 on 2021-12-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0003_santri_ktgri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='santri',
            old_name='ktgri',
            new_name='santri_ktgri',
        ),
    ]
