# Generated by Django 3.2.8 on 2021-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0003_rename_nama_pengarang_kitab_nama_pengarang'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitab',
            name='jenis_kitab',
            field=models.CharField(choices=[('Matan', 'Matan'), ('Nadhom', 'Nadhom')], default='', max_length=9),
        ),
        migrations.AddField(
            model_name='kitab',
            name='kategori_kitab',
            field=models.CharField(choices=[('Dasar', 'Dasar'), ('Menengah', 'Menengah'), ('Atas', 'Atas')], default='', max_length=9),
        ),
    ]
