# Generated by Django 3.2.8 on 2021-11-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0003_pengumuman'),
        ('adminpondok', '0004_auto_20211129_1419'),
    ]

    operations = [
    ]
