# Generated by Django 3.2.3 on 2021-12-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0004_rename_ktgri_santri_santri_ktgri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santri',
            name='santri_ktgri',
        ),
        migrations.AddField(
            model_name='santri',
            name='ktgri',
            field=models.CharField(choices=[('Quran', 'Al-Quran'), ('Matan', 'Matan'), ('Nadhom', 'Nadhom')], default='', max_length=8),
        ),
    ]
