# Generated by Django 3.2.8 on 2021-11-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0005_merge_0003_pengumuman_0004_auto_20211129_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitab',
            name='jenis_kitab',
            field=models.CharField(choices=[('Al-Quran', 'Al-Quran'), ('Matan', 'Matan'), ('Nadhom', 'Nadhom')], default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='kitab',
            name='kode_kitab',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kitab',
            name='nama_kitab',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='kitab',
            name='nama_pengarang',
            field=models.CharField(max_length=30),
        ),
    ]
