# Generated by Django 3.2.3 on 2021-12-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0005_auto_20211202_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
