# Generated by Django 3.2.3 on 2021-11-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0004_alter_santri_ktgri'),
        ('adminpondok', '0006_auto_20211129_1732'),
    ]

    operations = [
    ]
