# Generated by Django 3.2.8 on 2021-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.CharField(default='', max_length=12)),
                ('ayat', models.IntegerField(default=0)),
                ('juz', models.IntegerField(default=0)),
                ('halaman', models.IntegerField(default=0)),
                ('pengajar', models.CharField(default='', max_length=30)),
                ('keterangan', models.CharField(default=0, max_length=120)),
            ],
        ),
    ]
