# Generated by Django 3.2.8 on 2021-12-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitab', models.CharField(default=0, max_length=30)),
                ('bab', models.IntegerField(default=0)),
                ('halaman', models.IntegerField(default=0)),
                ('paragraf', models.IntegerField(default=0)),
                ('pengajar', models.CharField(default=0, max_length=30)),
                ('keterangan', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sorogan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitab', models.CharField(default='', max_length=30)),
                ('bab', models.IntegerField(default=0)),
                ('halaman', models.IntegerField(default=0)),
                ('paragraf', models.CharField(default='', max_length=20)),
                ('pengajar', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
