# Generated by Django 3.2.8 on 2021-12-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajar', '0002_auto_20211228_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadzom',
            name='kelancaran',
            field=models.CharField(default='', max_length=30),
        ),
    ]
