# Generated by Django 3.2.8 on 2021-12-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengajar', '0002_matan_sorogan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matan',
            new_name='Matan1',
        ),
    ]
