# Generated by Django 3.2.8 on 2021-12-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengajar', '0003_rename_matan_matan1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matan1',
            new_name='Matan',
        ),
    ]
