# Generated by Django 3.2.3 on 2022-01-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0017_auto_20220101_1506'),
        ('pengajar', '0005_auto_20220101_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandongan',
            name='kitab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandongan_matan', to='adminpondok.matan'),
        ),
        migrations.AlterField(
            model_name='sorogan',
            name='kitab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorogan_matan', to='adminpondok.matan'),
        ),
    ]
