# Generated by Django 3.2.3 on 2021-12-23 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0008_merge_0007_delete_kategori_0007_matan'),
        ('pengajar', '0006_nadzom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_santri', models.CharField(max_length=30)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termasuk', to='adminpondok.santri')),
            ],
        ),
    ]
