# Generated by Django 3.2.3 on 2022-01-01 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpondok', '0017_auto_20220101_1506'),
        ('pengajar', '0006_auto_20220101_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquran',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_quran', to='adminpondok.alquran'),
        ),
        migrations.AlterField(
            model_name='matan',
            name='kitab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_matan', to='adminpondok.matan'),
        ),
        migrations.AlterField(
            model_name='nadzom',
            name='kitab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_nadzom', to='adminpondok.nadzom'),
        ),
    ]
