# Generated by Django 3.2.3 on 2022-01-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajar', '0007_auto_20220101_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquran',
            name='surah',
        ),
        migrations.RemoveField(
            model_name='bandongan',
            name='kitab',
        ),
        migrations.RemoveField(
            model_name='matan',
            name='kitab',
        ),
        migrations.RemoveField(
            model_name='nadzom',
            name='kitab',
        ),
        migrations.RemoveField(
            model_name='sorogan',
            name='kitab',
        ),
        migrations.AlterField(
            model_name='alquran',
            name='pengajar',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bandongan',
            name='pengajar',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='matan',
            name='pengajar',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='nadzom',
            name='pengajar',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='sorogan',
            name='pengajar',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
