# Generated by Django 3.2.8 on 2021-12-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajar', '0007_santri'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandongan',
            name='tgl',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
