# Generated by Django 3.2.3 on 2021-12-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajar', '0010_alquran_tgl'),
    ]

    operations = [
        migrations.AddField(
            model_name='matan',
            name='tgl',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nadzom',
            name='tgl',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sorogan',
            name='tgl',
            field=models.DateField(auto_now=True),
        ),
    ]
